# Generated by Django 6.0.4 on 2026-05-05 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=1, unique=True)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("nome_guerra", models.CharField(max_length=50)),
                (
                    "posicao",
                    models.CharField(
                        choices=[
                            ("goleiro", "Goleiro"),
                            ("zagueiro", "Zagueiro"),
                            ("lateral", "Lateral"),
                            ("volante", "Volante"),
                            ("meia", "Meia"),
                            ("atacante", "Atacante"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_camisa",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(26),
                        ]
                    ),
                ),
                ("data_nascimento", models.DateField()),
                ("suspenso", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("nacionalidade", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("grupos", "Grupos"),
                            ("fase32", "Fase de 32"),
                            ("oitavas", "Oitavas"),
                            ("quartas", "Quartas"),
                            ("semifinal", "Semifinal"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("estadio", models.CharField(blank=True, max_length=150)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("gols_mandante", models.PositiveSmallIntegerField(default=0)),
                ("gols_visitante", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendado", "Agendado"),
                            ("em_andamento", "Em Andamento"),
                            ("encerrado", "Encerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="agendado",
                        max_length=20,
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="torneio.grupo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gol", "Gol"),
                            ("cartao_amarelo", "Cartão Amarelo"),
                            ("cartao_vermelho", "Cartão Vermelho"),
                            ("gol_contra", "Gol Contra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("minuto", models.PositiveSmallIntegerField()),
                ("acrescimo", models.BooleanField(default=False)),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos",
                        to="torneio.jogador",
                    ),
                ),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="torneio.jogo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Selecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=3, unique=True)),
                (
                    "confederacao",
                    models.CharField(
                        choices=[
                            ("UEFA", "UEFA"),
                            ("CONMEBOL", "CONMEBOL"),
                            ("CONCACAF", "CONCACAF"),
                            ("AFC", "AFC"),
                            ("CAF", "CAF"),
                            ("OFC", "OFC"),
                        ],
                        max_length=10,
                    ),
                ),
                ("escudo_url", models.URLField(blank=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selecoes",
                        to="torneio.grupo",
                    ),
                ),
                (
                    "tecnico",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selecao",
                        to="torneio.tecnico",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jogo",
            name="selecao_mandante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jogos_mandante",
                to="torneio.selecao",
            ),
        ),
        migrations.AddField(
            model_name="jogo",
            name="selecao_visitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jogos_visitante",
                to="torneio.selecao",
            ),
        ),
        migrations.AddField(
            model_name="jogador",
            name="selecao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jogadores",
                to="torneio.selecao",
            ),
        ),
    ]
